name: tpg
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - numpy=1.26.3
  - pip=23.3.1
  - python=3.11.7
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - torchaudio=2.2.0
  - torchtriton=2.2.0
  - torchvision=0.17.0
  - jupyter
  - pip:
      - absl-py==2.1.0
      - black[jupyter]
      - editdistance==0.8.1
      - emlangkit==0.2.0
      - isort==5.13.2
      - joblib==1.3.2
      - lightning==2.2.0.post0
      - matplotlib==3.8.3
      - numpyencoder==0.3.0
      - pandas==2.2.0
      - pre-commit==3.6.2
      - pyarrow==15.0.0
      - pytest==8.0.1
      - scikit-learn==1.4.1.post1
      - scikit_posthocs==0.9.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - shortuuid==1.0.11
      - statsmodels==0.14.1
      - tensorboard==2.16.2
      - torchmetrics==1.3.1
      - tqdm==4.66.2
      - wandb==0.16.3
